/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef file_CONSTANTS_H
#define file_CONSTANTS_H

#include "file_types.h"

namespace Test {

class fileConstants {
 public:
  fileConstants();

};

extern const fileConstants g_file_constants;

} // namespace

#endif
