/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "file_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace Test {


Url_req::~Url_req() throw() {
}


void Url_req::__set_url(const std::string& val) {
  this->url = val;
}

void Url_req::__set_force(const int32_t val) {
  this->force = val;
}

uint32_t Url_req::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->url);
          this->__isset.url = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->force);
          this->__isset.force = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Url_req::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Url_req");

  xfer += oprot->writeFieldBegin("url", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->url);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("force", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->force);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Url_req &a, Url_req &b) {
  using ::std::swap;
  swap(a.url, b.url);
  swap(a.force, b.force);
  swap(a.__isset, b.__isset);
}

Url_req::Url_req(const Url_req& other0) {
  url = other0.url;
  force = other0.force;
  __isset = other0.__isset;
}
Url_req& Url_req::operator=(const Url_req& other1) {
  url = other1.url;
  force = other1.force;
  __isset = other1.__isset;
  return *this;
}
void Url_req::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Url_req(";
  out << "url=" << to_string(url);
  out << ", " << "force=" << to_string(force);
  out << ")";
}

} // namespace
